=== asmodehn/sdlut/P0/Data/DTDs/Animation.dtd
<!ELEMENT Animation (Animation_TS_Filename, TS_ColorKey_RGB?, Sprite_Dimensions, Animation_Characteristics, Collision_Box_Modifier?)>
<!ELEMENT Animation_TS_Filename (#PCDATA)>
<!ELEMENT TS_ColorKey_RGB (ColorKey_R, ColorKey_G, ColorKey_B)>
<!ELEMENT ColorKey_R (#PCDATA)>
<!ELEMENT ColorKey_G (#PCDATA)>
<!ELEMENT ColorKey_B (#PCDATA)>
<!ELEMENT Sprite_Dimensions (Width, Height)>
<!ELEMENT Width (#PCDATA)>
<!ELEMENT Height (#PCDATA)>
<!ELEMENT Animation_Characteristics (Frames, Frames_Interval?)>
<!ELEMENT Frames (#PCDATA)>
<!ELEMENT Frames_Interval (#PCDATA)>
<!ELEMENT Collision_Box_Modifier (X_Modifier, Y_Modifier, W_Modifier, H_Modifier)>
<!ELEMENT X_Modifier (#PCDATA)>
<!ELEMENT Y_Modifier (#PCDATA)>
<!ELEMENT W_Modifier (#PCDATA)>
<!ELEMENT H_Modifier (#PCDATA)>

=== asmodehn/sdlut/P0/Data/Characters/Human_Unarmed_Run.xml
<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE Animation SYSTEM "../DTDs/Animation.dtd">

<Animation>
	<Animation_TS_Filename>Human Unarmed Run.png</Animation_TS_Filename>
	
	<TS_ColorKey_RGB>
		<ColorKey_R>106</ColorKey_R>
		<ColorKey_G>76</ColorKey_G>
		<ColorKey_B>48</ColorKey_B>
	</TS_ColorKey_RGB>
	
	<Sprite_Dimensions>
		<Width>96</Width>
		<Height>96</Height>
	</Sprite_Dimensions>

	<Animation_Characteristics>
		<Frames>9</Frames>
		<Frames_Interval>130</Frames_Interval>
	</Animation_Characteristics>
</Animation>

=== asmodehn/sdlut/P0/Data/Characters/Merchant_Talk.xml
<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE Animation SYSTEM "../DTDs/Animation.dtd">

<Animation>
	<Animation_TS_Filename>Merchant Talk.png</Animation_TS_Filename>
	
	<TS_ColorKey_RGB>
		<ColorKey_R>94</ColorKey_R>
		<ColorKey_G>66</ColorKey_G>
		<ColorKey_B>41</ColorKey_B>
	</TS_ColorKey_RGB>
	
	<Sprite_Dimensions>
		<Width>96</Width>
		<Height>96</Height>
	</Sprite_Dimensions>

	<Animation_Characteristics>
		<Frames>8</Frames>
		<KeyFrame>4</KeyFrame>
		<Frames_Interval>130</Frames_Interval>
	</Animation_Characteristics>
</Animation>
