=== asmodehn/sdlut/P0/Data/DTDs/Animations_Center.dtd
<!ELEMENT Animations_Center (Style, Type, Stop_Animation_Filename, Walk_Animation_Filename?, Run_Animation_Filename?, Attack_Animation_Filename?, Death_Animation_Filename?, Hit_Animation_Filename?, Pause_Animation_Filename?, Talk_Animation_Filename?)>
<!ELEMENT Style (#PCDATA)>
<!ELEMENT Type (#PCDATA)>
<!ELEMENT Stop_Animation_Filename (#PCDATA)>
<!ELEMENT Walk_Animation_Filename (#PCDATA)>
<!ELEMENT Run_Animation_Filename (#PCDATA)>
<!ELEMENT Attack_Animation_Filename (#PCDATA)>
<!ELEMENT Death_Animation_Filename (#PCDATA)>
<!ELEMENT Hit_Animation_Filename (#PCDATA)>
<!ELEMENT Pause_Animation_Filename (#PCDATA)>
<!ELEMENT Talk_Animation_Filename (#PCDATA)>

=== asmodehn/sdlut/P0/Data/Characters/Skeleton_Animations.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Animations_Center SYSTEM "../DTDs/Animations_Center.dtd">
<Animations_Center>
		<Style>Unarmed</Style><!-- Unarmed|Melee|Distant  ONLY !!-->
		<Type>Unarmed</Type><!-- Unarmed|Sword|Bow  ONLY !!-->
		<Stop_Animation_Filename>Skeleton_Stop.xml</Stop_Animation_Filename>
		<Walk_Animation_Filename>Skeleton_Walk.xml</Walk_Animation_Filename>
		<Run_Animation_Filename>Skeleton_Run.xml</Run_Animation_Filename>
		<Attack_Animation_Filename>Skeleton_Attack.xml</Attack_Animation_Filename>
		<Death_Animation_Filename>Skeleton_Death.xml</Death_Animation_Filename>
		<Hit_Animation_Filename>Skeleton_Hit.xml</Hit_Animation_Filename>
</Animations_Center>

=== asmodehn/sdlut/P0/Data/Characters/Human_Unarmed_Animations.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Animations_Center SYSTEM "../DTDs/Animations_Center.dtd">
<Animations_Center>
	<Style>Unarmed</Style><!-- Unarmed|Melee|Distant  ONLY !!-->
	<Type>Unarmed</Type><!-- Unarmed|Sword|Bow  ONLY !!-->
	<Stop_Animation_Filename>Human_Unarmed_Stop.xml</Stop_Animation_Filename>
	<Walk_Animation_Filename>Human_Unarmed_Walk.xml</Walk_Animation_Filename>
	<Run_Animation_Filename>Human_Unarmed_Run.xml</Run_Animation_Filename>
	<Attack_Animation_Filename>Human_Unarmed_Attack.xml</Attack_Animation_Filename>
	<Death_Animation_Filename>Human_Unarmed_Death.xml</Death_Animation_Filename>
	<Hit_Animation_Filename>Human_Unarmed_Hit.xml</Hit_Animation_Filename>
</Animations_Center>
