=== asmodehn/sdlut/P0/Data/DTDs/Animations.dtd
<!ELEMENT Animations (Style, Type, Attack_Animation_Filename, Death_Animation_Filename, Hit_Animation_Filename, Run_Animation_Filename?, Stop_Animation_Filename, Walk_Animation_Filename, Pause_Animation_Filename?)>
	<!ELEMENT Style (#PCDATA)>
	<!ELEMENT Type (#PCDATA)>
	<!ELEMENT Attack_Animation_Filename (#PCDATA)>
	<!ELEMENT Death_Animation_Filename (#PCDATA)>
	<!ELEMENT Hit_Animation_Filename (#PCDATA)>
	<!ELEMENT Run_Animation_Filename (#PCDATA)>
	<!ELEMENT Stop_Animation_Filename (#PCDATA)>
	<!ELEMENT Walk_Animation_Filename (#PCDATA)>
	<!ELEMENT Pause_Animation_Filename (#PCDATA)>

=== asmodehn/sdlut/P0/Data/Characters/Human_w_Bow_Animations.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Animations SYSTEM "../DTDs/Animations.dtd">
<Animations>
	<Style>Bow</Style>
	<Type>Distant</Type>
	<Attack_Animation_Filename>Human_w_Bow_Attack.xml</Attack_Animation_Filename>
	<Death_Animation_Filename>Human_w_Bow_Death.xml</Death_Animation_Filename>
	<Hit_Animation_Filename>Human_w_Bow_Hit.xml</Hit_Animation_Filename>
	<Run_Animation_Filename>Human_w_Bow_Run.xml</Run_Animation_Filename>
	<Stop_Animation_Filename>Human_w_Bow_Pause.xml</Stop_Animation_Filename>
	<Walk_Animation_Filename>Human_w_Bow_Walk.xml</Walk_Animation_Filename>
</Animations>

=== asmodehn/sdlut/P0/Data/Characters/Human_w_Sword_Animations.xml
<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE Animations SYSTEM "../DTDs/Animations.dtd">

<Animations>
	<Style>Sword</Style>
	<Type>Melee</Type>
	<Attack_Animation_Filename>Human_w_Sword_Attack.xml</Attack_Animation_Filename>
	<Death_Animation_Filename>Human_w_Sword_Death.xml</Death_Animation_Filename>
	<Hit_Animation_Filename>Human_w_Sword_Hit.xml</Hit_Animation_Filename>
	<Run_Animation_Filename>Human_w_Sword_Run.xml</Run_Animation_Filename>
	<Stop_Animation_Filename>Human_w_Sword_Stop.xml</Stop_Animation_Filename>
	<Walk_Animation_Filename>Human_w_Sword_Walk.xml</Walk_Animation_Filename>
</Animations>
