=== asmodehn/sdlut/P0/Data/DTDs/Character_Description.dtd
<!-- edited with XMLSpy v2007 sp2 (http://www.altova.com) by XfX (FWC) -->
<!ELEMENT Character_Description (Character_Type, Data_Root_Directory, Coords?, Allowed_Area?, Default_Sprite, Default_Collision_Box, Characteristics, Default_Animations)>
<!ELEMENT Character_Type (#PCDATA)>
<!ELEMENT Data_Root_Directory (#PCDATA)>
<!ELEMENT Coords (Initial_Position_X, Initial_Position_Y)>
<!ELEMENT Initial_Position_X (#PCDATA)>
<!ELEMENT Initial_Position_Y (#PCDATA)>
<!ELEMENT Allowed_Area (Allowed_Area_X, Allowed_Area_Y, Allowed_Area_W, Allowed_Area_H)>
<!ELEMENT Allowed_Area_X (#PCDATA)>
<!ELEMENT Allowed_Area_Y (#PCDATA)>
<!ELEMENT Allowed_Area_W (#PCDATA)>
<!ELEMENT Allowed_Area_H (#PCDATA)>
<!ELEMENT Default_Sprite (Default_Sprite_Width?, Default_Sprite_Height?)>
<!ELEMENT Default_Sprite_Width (#PCDATA)>
<!ELEMENT Default_Sprite_Height (#PCDATA)>
<!ELEMENT Default_Collision_Box (X_Modifier, Y_Modifier, CB_Width, CB_Height)>
<!ELEMENT X_Modifier (#PCDATA)>
<!ELEMENT Y_Modifier (#PCDATA)>
<!ELEMENT CB_Width (#PCDATA)>
<!ELEMENT CB_Height (#PCDATA)>
<!ELEMENT Characteristics (Velocity, Life, Armor, Damage)>
<!ELEMENT Velocity (#PCDATA)>
<!ELEMENT Life (#PCDATA)>
<!ELEMENT Armor (#PCDATA)>
<!ELEMENT Damage (#PCDATA)>
<!ELEMENT Default_Animations (Style, Type, Attack_Animation_Filename?, Death_Animation_Filename?, Hit_Animation_Filename?, Run_Animation_Filename?, Stop_Animation_Filename, Walk_Animation_Filename, Pause_Animation_Filename?, Talk_Animation_Filename?)>
<!ELEMENT Style (#PCDATA)>
<!ELEMENT Type (#PCDATA)>
<!ELEMENT Attack_Animation_Filename (#PCDATA)>
<!ELEMENT Death_Animation_Filename (#PCDATA)>
<!ELEMENT Hit_Animation_Filename (#PCDATA)>
<!ELEMENT Run_Animation_Filename (#PCDATA)>
<!ELEMENT Stop_Animation_Filename (#PCDATA)>
<!ELEMENT Walk_Animation_Filename (#PCDATA)>
<!ELEMENT Pause_Animation_Filename (#PCDATA)>
<!ELEMENT Talk_Animation_Filename (#PCDATA)>

=== asmodehn/sdlut/P0/Data/Characters/Player.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Character_Description SYSTEM "../DTDs/Character_Description.dtd">
<Character_Description>
	<Character_Type>Player</Character_Type>
	<Characters_ID>Humanoid</Characters_ID>
	<Data_Root_Directory>Data/Characters/</Data_Root_Directory>
	<Coords>
		<Initial_Position_X>192</Initial_Position_X>
		<Initial_Position_Y>224</Initial_Position_Y>
	</Coords>
	<Default_Sprite>
		<Default_Sprite_Width>96</Default_Sprite_Width>
		<Default_Sprite_Height>96</Default_Sprite_Height>
	</Default_Sprite>
	<Default_Collision_Box>
		<X_Modifier>+33</X_Modifier>
		<Y_Modifier>+20</Y_Modifier>
		<CB_Width>34</CB_Width>
		<CB_Height>59</CB_Height>
	</Default_Collision_Box>

	<Characteristics>
		<Velocity>120</Velocity><!-- Eceptionnaly it's in px/s coz its the player-->
		<Life>100</Life>
		<Armor>0</Armor>
		<Damage>20</Damage>
	</Characteristics>
	<Default_Animations>
		<Animation_Center_Filename>Human_Unarmed_Animations.xml</Animation_Center_Filename>
	</Default_Animations>
</Character_Description>

=== asmodehn/sdlut/P0/Data/Characters/Monster_Skeleton.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Character_Description SYSTEM "../DTDs/Character_Description.dtd">
<Character_Description>
	<Character_Type>Monster</Character_Type>
	<Characters_ID>Undead</Characters_ID>
	<Data_Root_Directory>Data/Characters/</Data_Root_Directory>
	<Default_Sprite>
		<Default_Sprite_Width>96</Default_Sprite_Width>
		<Default_Sprite_Height>96</Default_Sprite_Height>
	</Default_Sprite>
	<Default_Collision_Box>
		<X_Modifier>+30</X_Modifier>
		<Y_Modifier>+20</Y_Modifier>
		<CB_Width>35</CB_Width>
		<CB_Height>63</CB_Height>
	</Default_Collision_Box>

	<Characteristics>
		<Velocity>2</Velocity>
		<Life>100</Life>
		<Armor>0</Armor>
		<Damage>100</Damage>
	</Characteristics>
	<Default_Animations>
		<Animation_Center_Filename>Skeleton_Animations.xml</Animation_Center_Filename>
	</Default_Animations>
</Character_Description>

=== asmodehn/sdlut/P0/Data/Characters/NPC_Merchant.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Character_Description SYSTEM "../DTDs/Character_Description.dtd">
<Character_Description>
	<Character_Type>NPC</Character_Type>
	<Data_Root_Directory>Data/Characters/</Data_Root_Directory>
	<Coords>
		<Initial_Position_X>1088</Initial_Position_X>
		<Initial_Position_Y>352</Initial_Position_Y>
	</Coords>
	<Allowed_Area> <!-- Only allowed inside city walls -->
		<Allowed_Area_X>1056</Allowed_Area_X>
		<Allowed_Area_Y>320</Allowed_Area_Y>
		<Allowed_Area_W>160</Allowed_Area_W>
		<Allowed_Area_H>288</Allowed_Area_H>
	</Allowed_Area>
	<Default_Sprite>
		<Default_Sprite_Width>96</Default_Sprite_Width>
		<Default_Sprite_Height>96</Default_Sprite_Height>
	</Default_Sprite>
	<Default_Collision_Box>
		<X_Modifier>0</X_Modifier>
		<Y_Modifier>0</Y_Modifier>
		<CB_Width>96</CB_Width>
		<CB_Height>96</CB_Height>
	</Default_Collision_Box>

	<Characteristics>
		<Velocity>2</Velocity>
		<Life>100</Life>
		<Armor>0</Armor>
		<Damage>100</Damage>
	</Characteristics>
	<Default_Animations>
		<Animation_Center_Filename>Merchant_Animations.xml</Animation_Center_Filename>
	</Default_Animations>
</Character_Description>
